tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    php_code_sniffer: true
    php_changetracking: true
    sensiolabs_security_checker: true
    php_mess_detector: true
    external_code_coverage: true
filter:
    excluded_paths:
        - 'tests/*'